### ISSUE TITLE
The call instruction jumps to the previous version of the label once.

### ISSUE THREAD

**Issue by clucle** [hipkathon/hip-hop#5]
- 재현스탭

1. 아래 입력으로 루프를 도는 도중 멈춥니다.

```
  chill prev
  swaag
> swaag
  swaag
  call prev
```

2. 라벨을 변경후 재실행합니다.

```
  chill cur
  swaag
  swaag
  swaag
  call prev
```

점프되지 않아야 하지만, 한번 점프합니다

**Comment by lojpark** [comment]
mic drop 버튼 클릭 시 labels가 초기화되지 않아 발생한 버그로 보입니다.

**Comment by lojpark** [comment]
https://github.com/hipkathon/hip-hop/pull/6 PR으로 수정되었습니다. 감사합니다.
